/* Generated by scripts/build_site_data.py. Do not edit. */
export type AssertionKind = 'pass' | 'fail' | 'detail'
export type AssertionFamily = 'sequence' | 'arguments' | 'schema' | 'leakage'

export interface DisplayEvent {
  index: number
  role: string
  summary: string
  toolName: string | null
  arguments: Array<{ name: string; value: string }>
}

export interface AssertionLine { kind: AssertionKind; text: string }
export interface EvidenceSource { available: boolean; label: string; provenance: string | null; source: string | null }

export interface SiteData {
  available: boolean
  hero: { available: boolean; cassetteId: string | null; provider: string | null; model: string | null; eventCount: number | null; events: DisplayEvent[]; redactionCount: number | null; evidenceSource: EvidenceSource }
  library: { available: boolean; cassetteCount: number | null; providerCount: number | null; providers: string[]; redactionRuleCount: number | null }
  assertions: Record<AssertionFamily, { available: boolean; lines: AssertionLine[]; evidenceSource: EvidenceSource }>
  drift: { available: boolean; rows: Array<{ cassetteId: string; eventCount: number; classification: string; dimension: string | null }>; divergence: { cassetteId: string; dimension: string; expected: string; observed: string } | null; cassetteCount: number | null; regressionCount: number | null; evidenceSource: EvidenceSource }
  replay: { available: boolean; networkCalls: number | null; tokens: number | null; durationMs: number | null; evidenceSource: EvidenceSource }
}

export const cassetteData: SiteData = {
  "assertions": {
    "arguments": {
      "available": true,
      "evidenceSource": {
        "available": true,
        "label": "DETERMINISTIC LOCAL FIXTURE",
        "provenance": "Deterministic local Ferric demo fixture. Not provider or Kiro production traffic.",
        "source": "tests/cassettes/7390cec8b7a3c6af2cc1e019ae3d62d2ac8115c18451dc1f22669247c65c9fd2.json"
      },
      "lines": [
        {
          "kind": "pass",
          "text": "cassette 7390ce  critical month and threshold fields matched"
        },
        {
          "kind": "detail",
          "text": "expected  \"[REDACTED:card]\""
        }
      ]
    },
    "leakage": {
      "available": true,
      "evidenceSource": {
        "available": true,
        "label": "DETERMINISTIC LOCAL FIXTURE",
        "provenance": "Deterministic local Ferric demo fixture. Not provider or Kiro production traffic.",
        "source": "tests/cassettes/7390cec8b7a3c6af2cc1e019ae3d62d2ac8115c18451dc1f22669247c65c9fd2.json"
      },
      "lines": [
        {
          "kind": "pass",
          "text": "cassette 7390ce  0 declared secret matches across outbound fields"
        }
      ]
    },
    "schema": {
      "available": true,
      "evidenceSource": {
        "available": true,
        "label": "DETERMINISTIC LOCAL FIXTURE",
        "provenance": "Deterministic local Ferric demo fixture. Not provider or Kiro production traffic.",
        "source": "tests/cassettes/7390cec8b7a3c6af2cc1e019ae3d62d2ac8115c18451dc1f22669247c65c9fd2.json"
      },
      "lines": [
        {
          "kind": "pass",
          "text": "cassette 7390ce  structured anomaly result matched the local schema"
        }
      ]
    },
    "sequence": {
      "available": true,
      "evidenceSource": {
        "available": true,
        "label": "DETERMINISTIC LOCAL FIXTURE",
        "provenance": "Deterministic local Ferric demo fixture. Not provider or Kiro production traffic.",
        "source": "tests/cassettes/7390cec8b7a3c6af2cc1e019ae3d62d2ac8115c18451dc1f22669247c65c9fd2.json"
      },
      "lines": [
        {
          "kind": "pass",
          "text": "cassette 7390ce  tool sequence matched the recorded baseline"
        },
        {
          "kind": "detail",
          "text": "expected  [\"read_ledger\",\"flag_anomalies\",\"prepare_review\"]"
        },
        {
          "kind": "detail",
          "text": "observed  [\"read_ledger\",\"flag_anomalies\",\"prepare_review\"]"
        },
        {
          "kind": "detail",
          "text": "pattern  \"[REDACTED:api_key]\""
        },
        {
          "kind": "fail",
          "text": "cassette 7390ce  tool order diverged at index 0"
        },
        {
          "kind": "detail",
          "text": "expected  [\"read_ledger\",\"flag_anomalies\",\"prepare_review\"]"
        },
        {
          "kind": "detail",
          "text": "observed  [\"flag_anomalies\",\"read_ledger\",\"prepare_review\"]"
        }
      ]
    }
  },
  "available": true,
  "drift": {
    "available": true,
    "cassetteCount": 3,
    "divergence": {
      "cassetteId": "7390ce",
      "dimension": "tool_order",
      "expected": "read_ledger -> flag_anomalies -> prepare_review",
      "observed": "flag_anomalies -> read_ledger -> prepare_review"
    },
    "evidenceSource": {
      "available": true,
      "label": "DETERMINISTIC LOCAL FIXTURE",
      "provenance": "Deterministic local drift classification. Not a live provider capture. [REDACTED:bearer_token]",
      "source": "tests/cassettes/7390cec8b7a3c6af2cc1e019ae3d62d2ac8115c18451dc1f22669247c65c9fd2.json"
    },
    "regressionCount": 1,
    "rows": [
      {
        "cassetteId": "16774f",
        "classification": "unchanged",
        "dimension": null,
        "eventCount": 2
      },
      {
        "cassetteId": "7390ce",
        "classification": "diverged",
        "dimension": "tool_order",
        "eventCount": 11
      },
      {
        "cassetteId": "c6d236",
        "classification": "reworded",
        "dimension": null,
        "eventCount": 5
      }
    ]
  },
  "hero": {
    "available": true,
    "cassetteId": "7390ce",
    "eventCount": 11,
    "events": [
      {
        "arguments": [],
        "index": 0,
        "role": "user",
        "summary": "Reconcile a local ledger and prepare review evidence.",
        "toolName": null
      },
      {
        "arguments": [],
        "index": 1,
        "role": "user",
        "summary": "Reconcile the March ledger.",
        "toolName": null
      },
      {
        "arguments": [
          {
            "name": "month",
            "value": "\"2026-03\""
          }
        ],
        "index": 2,
        "role": "tool_call",
        "summary": "read_ledger(month=\"2026-03\")",
        "toolName": "read_ledger"
      },
      {
        "arguments": [],
        "index": 3,
        "role": "tool_result",
        "summary": "{\"rows\":1842}",
        "toolName": "read_ledger"
      },
      {
        "arguments": [],
        "index": 4,
        "role": "assistant",
        "summary": "The ledger is loaded. I will check the configured threshold.",
        "toolName": null
      },
      {
        "arguments": [
          {
            "name": "threshold",
            "value": "0.04"
          }
        ],
        "index": 5,
        "role": "tool_call",
        "summary": "flag_anomalies(threshold=0.04)",
        "toolName": "flag_anomalies"
      },
      {
        "arguments": [],
        "index": 6,
        "role": "tool_result",
        "summary": "{\"count\":3}",
        "toolName": "flag_anomalies"
      },
      {
        "arguments": [
          {
            "name": "count",
            "value": "3"
          },
          {
            "name": "month",
            "value": "\"2026-03\""
          }
        ],
        "index": 7,
        "role": "tool_call",
        "summary": "prepare_review(count=3, month=\"2026-03\")",
        "toolName": "prepare_review"
      },
      {
        "arguments": [],
        "index": 8,
        "role": "tool_result",
        "summary": "{\"review_id\":\"local-review-17\"}",
        "toolName": "prepare_review"
      },
      {
        "arguments": [],
        "index": 9,
        "role": "user",
        "summary": "Return the structured result.",
        "toolName": null
      },
      {
        "arguments": [],
        "index": 10,
        "role": "assistant",
        "summary": "{\"anomalies\":3,\"month\":\"2026-03\",\"review_id\":\"local-review-17\",\"rows\":1842}",
        "toolName": null
      }
    ],
    "evidenceSource": {
      "available": true,
      "label": "DETERMINISTIC LOCAL FIXTURE",
      "provenance": "Deterministic local Ferric demo fixture. Not provider or Kiro production traffic.",
      "source": "tests/cassettes/7390cec8b7a3c6af2cc1e019ae3d62d2ac8115c18451dc1f22669247c65c9fd2.json"
    },
    "model": "gpt-4.1-mini",
    "provider": "openai",
    "redactionCount": 4
  },
  "library": {
    "available": true,
    "cassetteCount": 4,
    "providerCount": 3,
    "providers": [
      "anthropic",
      "mcp",
      "openai"
    ],
    "redactionRuleCount": 4
  },
  "replay": {
    "available": true,
    "durationMs": 7,
    "evidenceSource": {
      "available": true,
      "label": "DETERMINISTIC LOCAL FIXTURE",
      "provenance": "Deterministic local replay duration for reproducible evidence. No provider transport was constructed. [REDACTED:email]",
      "source": "tests/cassettes/7390cec8b7a3c6af2cc1e019ae3d62d2ac8115c18451dc1f22669247c65c9fd2.json"
    },
    "networkCalls": 0,
    "tokens": 0
  }
}
